### PR TITLE
Allow Prometheus scrape interval to be configurable

### LINKED ISSUE #18: Need a way to adjust prometheus scrape interval
This needs to be configurable: https://github.com/redhat-service-assurance/smart-gateway-operator/blob/master/roles/smartgateway/tasks/servicemonitor.yml#L20

Reason is that we need to keep the prometheus scrape intervals slower (or at least equal to) the collectd interval[1], which may reasonably be set shorter than 1s.

This is possibly more of a concern for the upcoming https://github.com/redhat-service-assurance/service-assurance-operator  but this is where the setting currently exists, so I filed the issue here.

[1] "The period should be <= to the prometheus scrape period" https://github.com/redhat-service-assurance/smart-gateway/issues/42#issuecomment-542329154

### PR DESCRIPTION
**Pull request by leifmadsen**
Allows for the Prometheus scrape interval to be set by the operator when
instantiating the service monitors for a Prometheus instance. This is required
in order to set the rate that Prometheus will scrape the Smart Gateway for
metrics.

Closes #18

### CODE REVIEW

**Comment by leifmadsen** [comment]
Note that I did not test this.

**Comment by leifmadsen** [comment]
> LGTM (I didn't test it either). I assume the ansible version change will be okay?

Yea I don't think it should have any effect. It's really just metadata that isn't even really exposed because we never ship this to galaxy. The boilerplate was bothering me though.

**Comment by csibbitt** [comment]
@leifmadsen FYI this worked for me, though TBH I'm slightly surprised. You didn't add this option to the CRD, so I thought it should fail validation? I guess I assumed wrong. This SHOULD be added to the CRD, though, right?

Regardless, it seems to work:

* Deployed on quicklab
* Check I'm running latest SGO container with this patch
```
  $ oc describe po smart-gateway-operator-5984c64d88-9d6kp | grep Image
    Image:          docker-registry.default.svc:5000/sa-telemetry/smart-gateway-operator
    Image ID:       docker-pullable://docker-registry.default.svc:5000/sa-telemetry/smart-gateway-operator@sha256:8f02bf87439ab5ed515161f0dfa6618dc141289c11f5541ede82c1206dd21353
```
* `oc edit smartgateway cloud1-telemetry` and put `prometheus_scrape_interval: 14s` in the spec
* ...wait a bit...
* `oc get servicemonitor smartgateway -o yaml | grep interval`
  - interval: 14s
```
$ curl --silent http://prometheus-sa-telemetry.apps.safperf001.lab.pnq2.cee.redhat.com/config | grep -A 2 "job_name: sa-telemetry/smartgateway"
- job_name: sa-telemetry/smartgateway/0
  scrape_interval: 14s
  scrape_timeout: 10s
```

**Comment by leifmadsen** [comment]
@csibbitt oh right, yes I forgot about the CRD!!! And I'm not sure about the validation part. I know that even if you don't have any validation setup, that the Ansible Operator will just happily let you pass in whatever you want, and that it will convert the CamelCase input into a snake_case automatically...

I'll look and see if there is some sort of flag that can be set so that the Ansible Operator requires validation against the CRD to pass...

**Comment by leifmadsen** [comment]
OK I was asking in the #ansible-operator channel and got some really good information:

* https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
* https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

Long story short, the CRD is working as intended for the version of k8s and for the method that we're using in the CRD.

There is no automatic rejection; it'll only validate on fields that you specify and check against those. So for example, it'll check `spec.size` and will reject if you pass `spec.size: 'hello world'` (non integer), but `spec.siez` will be passed through without any validation (since it isn't specified).

Going forward (k8s 1.15) a structural schema can be implemented that will allow the failing of CRs that don't meet the structured schema specified in the CRD. For 1.15 under the `apiextensions.k8s.io/v1beta1` API you can create a structural schema, and then use `preserveUnknownFields: false` which will result in them not being stored (available to the operator). Structural schemas will be required in k8s 1.16 if using the `v1` version of the API.

**Pull request merged**
